version: "3"

services:
  httpd_conf_1:
    build:
      context: image/httpd
    volumes:
      - ./httpd/htdocs:/var/www/html:z
      - ./httpd/mod_ldap.conf.v1:/etc/httpd/conf.d/mod_ldap.conf:z
      - ./httpd/config_alias.conf:/etc/httpd/conf.d/config_alias.conf:z
    ports:
      - "8081:8080"

  httpd_conf_2:
    build:
      context: image/httpd
    volumes:
      - ./httpd/htdocs:/var/www/html:z
      - ./httpd/mod_ldap.conf.v2:/etc/httpd/conf.d/mod_ldap.conf:z
      - ./httpd/config_alias.conf:/etc/httpd/conf.d/config_alias.conf:z
    ports:
      - "8082:8080"

  httpd_conf_3:
    build:
      context: image/httpd
    volumes:
      - ./httpd/htdocs:/var/www/html:z
      - ./httpd/mod_ldap.conf.v3:/etc/httpd/conf.d/mod_ldap.conf:z
      - ./httpd/config_alias.conf:/etc/httpd/conf.d/config_alias.conf:z
    ports:
      - "8083:8080"

  ldap:
    image: slapd
    environment:
      LDAP_DEBUG_LEVEL: 0
    volumes:
      - ./ldap/config:/docker-entrypoint.d
