version: "3"

services:
  httpd_conf_1:
    image: docker.io/httpd:2.4.54
    volumes:
      - ./httpd/htdocs:/usr/local/apache2/htdocs/:z
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:z
      - ./httpd/mod_ldap.conf.v1:/usr/local/apache2/conf/mod_ldap.conf:z
    ports:
      - "8081:80"

  httpd_conf_2:
    image: docker.io/httpd:2.4.54
    volumes:
      - ./httpd/htdocs:/usr/local/apache2/htdocs/:z
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:z
      - ./httpd/mod_ldap.conf.v2:/usr/local/apache2/conf/mod_ldap.conf:z
    ports:
      - "8082:80"

  httpd_conf_3:
    image: docker.io/httpd:2.4.54
    volumes:
      - ./httpd/htdocs:/usr/local/apache2/htdocs/:z
      - ./httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf:z
      - ./httpd/mod_ldap.conf.v3:/usr/local/apache2/conf/mod_ldap.conf:z
    ports:
      - "8083:80"

  ldap:
    image: slapd
    environment:
      LDAP_DEBUG_LEVEL: 0
    volumes:
      - ./ldap/config:/docker-entrypoint.d
